kind: StorageClass  
apiVersion: storage.k8s.io/v1beta1  
metadata:  
 name: fast  
provisioner: kubernetes.io/gce-pd  
parameters:  
 type: pd-ssd
---
kind: Service
apiVersion: v1
metadata:
 name: mongo
spec:
 ports:
 - port: 27017
 selector:
   role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: development
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: proposal-mongo-sidecar
          image: austbot/mongo-k8s-sidecar
          env:
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo"
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=development"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi
